security:
  oauth2:
    client:
      clientId: YOUR FB APP CLIENT ID HERE
      clientSecret: YOUR FB APP CLIENT SECRET HERE
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me    
     
spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        url: jdbc:mysql://localhost:3306/easwarDb
        username: root
        password: easwaran
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        view:
          prefix: /WEB-INF/views/
          suffix: .jsp
    resources:
        add-mappings: true        
        static-locations: /WEB-INF/resources/
        
application:
    view:
        mobile-name: "Easwar"

error:
  whitelabel:
    enabled: false
